
import re
import os

portfolio_path = '/Users/labc12/Documents/uriisace-main/portfolio.html'

with open(portfolio_path, 'r') as f:
    content = f.read()

# 1. Remove the "Foto urielo" item
# We look for the block containing "Foto urielo.png"
# The block is <div class="apo-item ..."> ... <img src="...Foto urielo.png" ...> ... </div>
# We need to act carefully to remove the whole parent div.
# Since the HTML structure is consistent (generated by my previous script), we can try to match the specific block pattern.

# Pattern to find the specific div block for Foto urielo
# It starts with <div class="apo-item and ends with </div>, and contains Foto urielo.png
# We'll use a regex that matches the standard block structure we generated.
# Our generated blocks look like:
# <div class="apo-item ...">\n<article ...>\n...Foto urielo.png...\n...</article>\n</div>
feature_pattern = re.compile(
    r'<div class="apo-item [^"]*">\s*<article class="apo-project">.*?Foto urielo\.png.*?</article>\s*</div>',
    re.DOTALL
)

if feature_pattern.search(content):
    print("Found Foto urielo item. Removing...")
    content = feature_pattern.sub('', content)
else:
    print("Foto urielo item not found using strict block match. Trying simpler removal or it might be gone.")

# 2. Fix Titles
# Titles identify as <h2 class="apo-project-title"><a href="#">FILENAME...</a></h2>
# We want to change FILENAME to Title Case, remove underscores/dashes, remove extensions.

def fix_title(match):
    full_tag = match.group(0)
    # Extract the text inside the anchor
    title_match = re.search(r'<a href="#">(.*?)</a>', full_tag)
    if not title_match:
        return full_tag
    
    raw_title = title_match.group(1)
    
    # Check if it looks like a filename (has extension)
    # We clean it even if it was truncated with ...
    clean_title = raw_title
    
    # Remove ellipsis ... if present at end (added by my previous script)
    if clean_title.endswith('...'):
        clean_title = clean_title[:-3]
    
    # Remove extension if present
    clean_title = re.sub(r'\.(jpg|jpeg|png|mp4|gif)$', '', clean_title, flags=re.IGNORECASE)
    
    # Replace separators with spaces
    clean_title = clean_title.replace('_', ' ').replace('-', ' ')
    
    # Split camelCase if possible? (Optional, maybe too risky)
    # Let's just do basics first.
    
    # Lowercase and Capitalize properly
    clean_title = clean_title.title()
    
    return f'<h2 class="apo-project-title"><a href="#">{clean_title}</a></h2>'

# Regex to find the title tags
title_pattern = re.compile(r'<h2 class="apo-project-title"><a href="#">.*?</a></h2>')

content = title_pattern.sub(fix_title, content)

with open(portfolio_path, 'w') as f:
    f.write(content)

print("Portfolio updated.")
